# Generated by Django 4.0.2 on 2022-02-19 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_managers_alter_post_publicado'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
